name: Macaca
slogen: Solution for Automation Test with Ease

collections:
  docs:
    output: true
    permalink: /macaca/:path.html

defaults:
  -
    scope:
      path: "_docs"
    values:
      layout: docs

timezone: Asia/Shanghai

sass:
  # style: expanded
  style: compressed

# gems:
#   - jemoji
